@startuml
actor Admin
participant UI
participant InventoryController
database Database

Admin -> UI: Add Inventory
UI -> InventoryController: Send Inventory Information
InventoryController -> Database: Check duplicate Inventory
Database --> InventoryController: Return result of Duplicate

alt Inventory Duplicated
    InventoryController --> UI: Return Invalid Inventory
    UI --> Admin: Show Invalid Message
else Inventory Valid
    InventoryController -> Database: Send Inventory
    Database -> Database: Add Inventory to DB
    Database --> InventoryController: Return adding result
    InventoryController --> UI: Sending result to User
    UI --> Admin: Show Result Message
end
@enduml