@startuml
actor Admin
participant UI
participant InventoryController
database Database

Admin -> UI: Change Inventory
UI -> InventoryController: Post Change
InventoryController -> Database: Check Valid Inventory
Database -> Database: Check Inventory Information
Database --> InventoryController: Return result

alt Invalid Inventory
    InventoryController --> UI: Return Invalid Inventory
    UI --> Admin: Show Invalid Message
else Valid Inventory
    InventoryController -> Database: Send Changes
    Database -> Database: Update to Inventory
    Database --> InventoryController: Return Changing result
    InventoryController --> UI: Sending result to User
    UI --> Admin: Show Result Message
end
@enduml